# Generated by Django 5.2.1 on 2025-06-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('validated_by_vet', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('AI', 'IA'), ('vet', 'Vétérinaire')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='consultations.consultation')),
            ],
        ),
    ]
